title: Fantographics
description: "Typography Within Fantasy "
footer_text: "Copyright 2021 Oliver Evans "
header_feature_image: ../uploads/patrick-hendry-wtfi19lwj1s-unsplash.jpg
header_text: "Typography Within Fantasy "
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/add-a-heading.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items: []
